version: '3.9'

services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: wordpass
      POSTGRES_DB: pgdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  db_test:
    image: postgres:17.2
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: wordpass
      POSTGRES_DB: pgdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local